#!/bin/bash

export THEANO_FLAGS='floatX=float32,blas.ldflags="-L/data1/u/abeaucha/.local/lib/python2.7/site-packages/numpy/.libs/ -lopenblasp-r0-39a31c03.2.18"'
script_loc=$(readlink -f ../../projects/unsupervised)

hdf5file=${1:-./unsorted.hdf5}
test_dir=${2:-./test1}


# steal a file to put in the test dir

hdfdirname=$(basename $hdf5file .hdf5)
hdfdir=$(dirname $hdf5file)/$hdfdirname
test_file=$(find $hdfdir -type f -name '*.sio' | head -n 1)
test -e "$test_file" || { echo "No dummy data directory found! "; exit; }

# fake a test dir
rm -r $test_dir
mkdir -p $test_dir
cp $test_file $test_dir/

date
ipython --pdb $script_loc/classifySAETrainer.py -- --neuron 1000 200 --learnF .12 .12 --momentumF .5 .5 --dropoutF .8 1. --batch 200 --epoch 1 --target $test_dir $hdf5file 
date
